package com.mysupermarket.pojo;

public class BuyCar {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_car.bc_id
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private Integer bcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_car.bc_goodnum
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private Integer bcGoodnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_car.bc_useraccount
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private Integer bcUseraccount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_car.bc_id
     *
     * @return the value of buy_car.bc_id
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public Integer getBcId() {
        return bcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_car.bc_id
     *
     * @param bcId the value for buy_car.bc_id
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setBcId(Integer bcId) {
        this.bcId = bcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_car.bc_goodnum
     *
     * @return the value of buy_car.bc_goodnum
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public Integer getBcGoodnum() {
        return bcGoodnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_car.bc_goodnum
     *
     * @param bcGoodnum the value for buy_car.bc_goodnum
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setBcGoodnum(Integer bcGoodnum) {
        this.bcGoodnum = bcGoodnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_car.bc_useraccount
     *
     * @return the value of buy_car.bc_useraccount
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public Integer getBcUseraccount() {
        return bcUseraccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_car.bc_useraccount
     *
     * @param bcUseraccount the value for buy_car.bc_useraccount
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setBcUseraccount(Integer bcUseraccount) {
        this.bcUseraccount = bcUseraccount;
    }
}