package com.mysupermarket.pojo;

import java.util.ArrayList;
import java.util.List;

public class BuyCarExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table buy_car
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table buy_car
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table buy_car
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_car
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public BuyCarExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_car
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_car
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_car
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_car
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_car
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_car
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_car
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_car
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_car
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_car
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table buy_car
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBcIdIsNull() {
            addCriterion("bc_id is null");
            return (Criteria) this;
        }

        public Criteria andBcIdIsNotNull() {
            addCriterion("bc_id is not null");
            return (Criteria) this;
        }

        public Criteria andBcIdEqualTo(Integer value) {
            addCriterion("bc_id =", value, "bcId");
            return (Criteria) this;
        }

        public Criteria andBcIdNotEqualTo(Integer value) {
            addCriterion("bc_id <>", value, "bcId");
            return (Criteria) this;
        }

        public Criteria andBcIdGreaterThan(Integer value) {
            addCriterion("bc_id >", value, "bcId");
            return (Criteria) this;
        }

        public Criteria andBcIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("bc_id >=", value, "bcId");
            return (Criteria) this;
        }

        public Criteria andBcIdLessThan(Integer value) {
            addCriterion("bc_id <", value, "bcId");
            return (Criteria) this;
        }

        public Criteria andBcIdLessThanOrEqualTo(Integer value) {
            addCriterion("bc_id <=", value, "bcId");
            return (Criteria) this;
        }

        public Criteria andBcIdIn(List<Integer> values) {
            addCriterion("bc_id in", values, "bcId");
            return (Criteria) this;
        }

        public Criteria andBcIdNotIn(List<Integer> values) {
            addCriterion("bc_id not in", values, "bcId");
            return (Criteria) this;
        }

        public Criteria andBcIdBetween(Integer value1, Integer value2) {
            addCriterion("bc_id between", value1, value2, "bcId");
            return (Criteria) this;
        }

        public Criteria andBcIdNotBetween(Integer value1, Integer value2) {
            addCriterion("bc_id not between", value1, value2, "bcId");
            return (Criteria) this;
        }

        public Criteria andBcGoodnumIsNull() {
            addCriterion("bc_goodnum is null");
            return (Criteria) this;
        }

        public Criteria andBcGoodnumIsNotNull() {
            addCriterion("bc_goodnum is not null");
            return (Criteria) this;
        }

        public Criteria andBcGoodnumEqualTo(Integer value) {
            addCriterion("bc_goodnum =", value, "bcGoodnum");
            return (Criteria) this;
        }

        public Criteria andBcGoodnumNotEqualTo(Integer value) {
            addCriterion("bc_goodnum <>", value, "bcGoodnum");
            return (Criteria) this;
        }

        public Criteria andBcGoodnumGreaterThan(Integer value) {
            addCriterion("bc_goodnum >", value, "bcGoodnum");
            return (Criteria) this;
        }

        public Criteria andBcGoodnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("bc_goodnum >=", value, "bcGoodnum");
            return (Criteria) this;
        }

        public Criteria andBcGoodnumLessThan(Integer value) {
            addCriterion("bc_goodnum <", value, "bcGoodnum");
            return (Criteria) this;
        }

        public Criteria andBcGoodnumLessThanOrEqualTo(Integer value) {
            addCriterion("bc_goodnum <=", value, "bcGoodnum");
            return (Criteria) this;
        }

        public Criteria andBcGoodnumIn(List<Integer> values) {
            addCriterion("bc_goodnum in", values, "bcGoodnum");
            return (Criteria) this;
        }

        public Criteria andBcGoodnumNotIn(List<Integer> values) {
            addCriterion("bc_goodnum not in", values, "bcGoodnum");
            return (Criteria) this;
        }

        public Criteria andBcGoodnumBetween(Integer value1, Integer value2) {
            addCriterion("bc_goodnum between", value1, value2, "bcGoodnum");
            return (Criteria) this;
        }

        public Criteria andBcGoodnumNotBetween(Integer value1, Integer value2) {
            addCriterion("bc_goodnum not between", value1, value2, "bcGoodnum");
            return (Criteria) this;
        }

        public Criteria andBcUseraccountIsNull() {
            addCriterion("bc_useraccount is null");
            return (Criteria) this;
        }

        public Criteria andBcUseraccountIsNotNull() {
            addCriterion("bc_useraccount is not null");
            return (Criteria) this;
        }

        public Criteria andBcUseraccountEqualTo(Integer value) {
            addCriterion("bc_useraccount =", value, "bcUseraccount");
            return (Criteria) this;
        }

        public Criteria andBcUseraccountNotEqualTo(Integer value) {
            addCriterion("bc_useraccount <>", value, "bcUseraccount");
            return (Criteria) this;
        }

        public Criteria andBcUseraccountGreaterThan(Integer value) {
            addCriterion("bc_useraccount >", value, "bcUseraccount");
            return (Criteria) this;
        }

        public Criteria andBcUseraccountGreaterThanOrEqualTo(Integer value) {
            addCriterion("bc_useraccount >=", value, "bcUseraccount");
            return (Criteria) this;
        }

        public Criteria andBcUseraccountLessThan(Integer value) {
            addCriterion("bc_useraccount <", value, "bcUseraccount");
            return (Criteria) this;
        }

        public Criteria andBcUseraccountLessThanOrEqualTo(Integer value) {
            addCriterion("bc_useraccount <=", value, "bcUseraccount");
            return (Criteria) this;
        }

        public Criteria andBcUseraccountIn(List<Integer> values) {
            addCriterion("bc_useraccount in", values, "bcUseraccount");
            return (Criteria) this;
        }

        public Criteria andBcUseraccountNotIn(List<Integer> values) {
            addCriterion("bc_useraccount not in", values, "bcUseraccount");
            return (Criteria) this;
        }

        public Criteria andBcUseraccountBetween(Integer value1, Integer value2) {
            addCriterion("bc_useraccount between", value1, value2, "bcUseraccount");
            return (Criteria) this;
        }

        public Criteria andBcUseraccountNotBetween(Integer value1, Integer value2) {
            addCriterion("bc_useraccount not between", value1, value2, "bcUseraccount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table buy_car
     *
     * @mbggenerated do_not_delete_during_merge Sun Aug 06 09:44:18 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table buy_car
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}