package com.mysupermarket.pojo;

public class GoodDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_detail.gd_id
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private Integer gdId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_detail.gd_url
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private String gdUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_detail.gd_primeprice
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private Double gdPrimeprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_detail.gd_freight
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private Double gdFreight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_detail.gd_choose
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private String gdChoose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_detail.gd_shop
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private Integer gdShop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_detail.gd_good
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private Integer gdGood;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_detail.gd_id
     *
     * @return the value of good_detail.gd_id
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public Integer getGdId() {
        return gdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_detail.gd_id
     *
     * @param gdId the value for good_detail.gd_id
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setGdId(Integer gdId) {
        this.gdId = gdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_detail.gd_url
     *
     * @return the value of good_detail.gd_url
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public String getGdUrl() {
        return gdUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_detail.gd_url
     *
     * @param gdUrl the value for good_detail.gd_url
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setGdUrl(String gdUrl) {
        this.gdUrl = gdUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_detail.gd_primeprice
     *
     * @return the value of good_detail.gd_primeprice
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public Double getGdPrimeprice() {
        return gdPrimeprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_detail.gd_primeprice
     *
     * @param gdPrimeprice the value for good_detail.gd_primeprice
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setGdPrimeprice(Double gdPrimeprice) {
        this.gdPrimeprice = gdPrimeprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_detail.gd_freight
     *
     * @return the value of good_detail.gd_freight
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public Double getGdFreight() {
        return gdFreight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_detail.gd_freight
     *
     * @param gdFreight the value for good_detail.gd_freight
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setGdFreight(Double gdFreight) {
        this.gdFreight = gdFreight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_detail.gd_choose
     *
     * @return the value of good_detail.gd_choose
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public String getGdChoose() {
        return gdChoose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_detail.gd_choose
     *
     * @param gdChoose the value for good_detail.gd_choose
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setGdChoose(String gdChoose) {
        this.gdChoose = gdChoose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_detail.gd_shop
     *
     * @return the value of good_detail.gd_shop
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public Integer getGdShop() {
        return gdShop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_detail.gd_shop
     *
     * @param gdShop the value for good_detail.gd_shop
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setGdShop(Integer gdShop) {
        this.gdShop = gdShop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_detail.gd_good
     *
     * @return the value of good_detail.gd_good
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public Integer getGdGood() {
        return gdGood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_detail.gd_good
     *
     * @param gdGood the value for good_detail.gd_good
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setGdGood(Integer gdGood) {
        this.gdGood = gdGood;
    }
}