package com.mysupermarket.pojo;

public class Good {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.g_id
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private Integer gId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.g_name
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private String gName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.g_url
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private String gUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.g_price
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private Double gPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.g_sales
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private Integer gSales;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.g_remain
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private Integer gRemain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good.g_kind
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private Integer gKind;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.g_id
     *
     * @return the value of good.g_id
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public Integer getgId() {
        return gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.g_id
     *
     * @param gId the value for good.g_id
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setgId(Integer gId) {
        this.gId = gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.g_name
     *
     * @return the value of good.g_name
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public String getgName() {
        return gName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.g_name
     *
     * @param gName the value for good.g_name
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setgName(String gName) {
        this.gName = gName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.g_url
     *
     * @return the value of good.g_url
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public String getgUrl() {
        return gUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.g_url
     *
     * @param gUrl the value for good.g_url
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setgUrl(String gUrl) {
        this.gUrl = gUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.g_price
     *
     * @return the value of good.g_price
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public Double getgPrice() {
        return gPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.g_price
     *
     * @param gPrice the value for good.g_price
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setgPrice(Double gPrice) {
        this.gPrice = gPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.g_sales
     *
     * @return the value of good.g_sales
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public Integer getgSales() {
        return gSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.g_sales
     *
     * @param gSales the value for good.g_sales
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setgSales(Integer gSales) {
        this.gSales = gSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.g_remain
     *
     * @return the value of good.g_remain
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public Integer getgRemain() {
        return gRemain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.g_remain
     *
     * @param gRemain the value for good.g_remain
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setgRemain(Integer gRemain) {
        this.gRemain = gRemain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good.g_kind
     *
     * @return the value of good.g_kind
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public Integer getgKind() {
        return gKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good.g_kind
     *
     * @param gKind the value for good.g_kind
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setgKind(Integer gKind) {
        this.gKind = gKind;
    }
}