package com.mysupermarket.pojo;

public class GoodEvaluate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_evaluate.gdl_id
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private Integer gdlId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_evaluate.gdl_date
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private String gdlDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_evaluate.gdl_chose
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private String gdlChose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_evaluate.gdl_content
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private String gdlContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_evaluate.gdl_good
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private Integer gdlGood;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_evaluate.gdl_useraccount
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private Integer gdlUseraccount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_evaluate.gdl_id
     *
     * @return the value of good_evaluate.gdl_id
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public Integer getGdlId() {
        return gdlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_evaluate.gdl_id
     *
     * @param gdlId the value for good_evaluate.gdl_id
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setGdlId(Integer gdlId) {
        this.gdlId = gdlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_evaluate.gdl_date
     *
     * @return the value of good_evaluate.gdl_date
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public String getGdlDate() {
        return gdlDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_evaluate.gdl_date
     *
     * @param gdlDate the value for good_evaluate.gdl_date
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setGdlDate(String gdlDate) {
        this.gdlDate = gdlDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_evaluate.gdl_chose
     *
     * @return the value of good_evaluate.gdl_chose
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public String getGdlChose() {
        return gdlChose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_evaluate.gdl_chose
     *
     * @param gdlChose the value for good_evaluate.gdl_chose
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setGdlChose(String gdlChose) {
        this.gdlChose = gdlChose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_evaluate.gdl_content
     *
     * @return the value of good_evaluate.gdl_content
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public String getGdlContent() {
        return gdlContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_evaluate.gdl_content
     *
     * @param gdlContent the value for good_evaluate.gdl_content
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setGdlContent(String gdlContent) {
        this.gdlContent = gdlContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_evaluate.gdl_good
     *
     * @return the value of good_evaluate.gdl_good
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public Integer getGdlGood() {
        return gdlGood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_evaluate.gdl_good
     *
     * @param gdlGood the value for good_evaluate.gdl_good
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setGdlGood(Integer gdlGood) {
        this.gdlGood = gdlGood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_evaluate.gdl_useraccount
     *
     * @return the value of good_evaluate.gdl_useraccount
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public Integer getGdlUseraccount() {
        return gdlUseraccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_evaluate.gdl_useraccount
     *
     * @param gdlUseraccount the value for good_evaluate.gdl_useraccount
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setGdlUseraccount(Integer gdlUseraccount) {
        this.gdlUseraccount = gdlUseraccount;
    }
}