package com.mysupermarket.pojo;

public class GoodBuycar extends GoodBuycarKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_buycar.gbc_goodchoose
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private String gbcGoodchoose;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_buycar.gbc_goodchoose
     *
     * @return the value of good_buycar.gbc_goodchoose
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public String getGbcGoodchoose() {
        return gbcGoodchoose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_buycar.gbc_goodchoose
     *
     * @param gbcGoodchoose the value for good_buycar.gbc_goodchoose
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setGbcGoodchoose(String gbcGoodchoose) {
        this.gbcGoodchoose = gbcGoodchoose;
    }
}