package com.mysupermarket.pojo;

public class GoodBuycarKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_buycar.gbc_buycar
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private Integer gbcBuycar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_buycar.gbc_good
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private Integer gbcGood;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_buycar.gbc_buycar
     *
     * @return the value of good_buycar.gbc_buycar
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public Integer getGbcBuycar() {
        return gbcBuycar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_buycar.gbc_buycar
     *
     * @param gbcBuycar the value for good_buycar.gbc_buycar
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setGbcBuycar(Integer gbcBuycar) {
        this.gbcBuycar = gbcBuycar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_buycar.gbc_good
     *
     * @return the value of good_buycar.gbc_good
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public Integer getGbcGood() {
        return gbcGood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_buycar.gbc_good
     *
     * @param gbcGood the value for good_buycar.gbc_good
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setGbcGood(Integer gbcGood) {
        this.gbcGood = gbcGood;
    }
}