package com.mysupermarket.pojo;

public class GoodKind {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_kind.gk_id
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private Integer gkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_kind.gk_name
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private String gkName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column good_kind.gk_comment
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private String gkComment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_kind.gk_id
     *
     * @return the value of good_kind.gk_id
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public Integer getGkId() {
        return gkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_kind.gk_id
     *
     * @param gkId the value for good_kind.gk_id
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setGkId(Integer gkId) {
        this.gkId = gkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_kind.gk_name
     *
     * @return the value of good_kind.gk_name
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public String getGkName() {
        return gkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_kind.gk_name
     *
     * @param gkName the value for good_kind.gk_name
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setGkName(String gkName) {
        this.gkName = gkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column good_kind.gk_comment
     *
     * @return the value of good_kind.gk_comment
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public String getGkComment() {
        return gkComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column good_kind.gk_comment
     *
     * @param gkComment the value for good_kind.gk_comment
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setGkComment(String gkComment) {
        this.gkComment = gkComment;
    }
}