package com.mysupermarket.pojo;

import java.util.ArrayList;
import java.util.List;

public class GoodKindExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table good_kind
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table good_kind
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table good_kind
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_kind
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public GoodKindExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_kind
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_kind
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_kind
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_kind
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_kind
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_kind
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_kind
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_kind
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_kind
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_kind
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table good_kind
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGkIdIsNull() {
            addCriterion("gk_id is null");
            return (Criteria) this;
        }

        public Criteria andGkIdIsNotNull() {
            addCriterion("gk_id is not null");
            return (Criteria) this;
        }

        public Criteria andGkIdEqualTo(Integer value) {
            addCriterion("gk_id =", value, "gkId");
            return (Criteria) this;
        }

        public Criteria andGkIdNotEqualTo(Integer value) {
            addCriterion("gk_id <>", value, "gkId");
            return (Criteria) this;
        }

        public Criteria andGkIdGreaterThan(Integer value) {
            addCriterion("gk_id >", value, "gkId");
            return (Criteria) this;
        }

        public Criteria andGkIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("gk_id >=", value, "gkId");
            return (Criteria) this;
        }

        public Criteria andGkIdLessThan(Integer value) {
            addCriterion("gk_id <", value, "gkId");
            return (Criteria) this;
        }

        public Criteria andGkIdLessThanOrEqualTo(Integer value) {
            addCriterion("gk_id <=", value, "gkId");
            return (Criteria) this;
        }

        public Criteria andGkIdIn(List<Integer> values) {
            addCriterion("gk_id in", values, "gkId");
            return (Criteria) this;
        }

        public Criteria andGkIdNotIn(List<Integer> values) {
            addCriterion("gk_id not in", values, "gkId");
            return (Criteria) this;
        }

        public Criteria andGkIdBetween(Integer value1, Integer value2) {
            addCriterion("gk_id between", value1, value2, "gkId");
            return (Criteria) this;
        }

        public Criteria andGkIdNotBetween(Integer value1, Integer value2) {
            addCriterion("gk_id not between", value1, value2, "gkId");
            return (Criteria) this;
        }

        public Criteria andGkNameIsNull() {
            addCriterion("gk_name is null");
            return (Criteria) this;
        }

        public Criteria andGkNameIsNotNull() {
            addCriterion("gk_name is not null");
            return (Criteria) this;
        }

        public Criteria andGkNameEqualTo(String value) {
            addCriterion("gk_name =", value, "gkName");
            return (Criteria) this;
        }

        public Criteria andGkNameNotEqualTo(String value) {
            addCriterion("gk_name <>", value, "gkName");
            return (Criteria) this;
        }

        public Criteria andGkNameGreaterThan(String value) {
            addCriterion("gk_name >", value, "gkName");
            return (Criteria) this;
        }

        public Criteria andGkNameGreaterThanOrEqualTo(String value) {
            addCriterion("gk_name >=", value, "gkName");
            return (Criteria) this;
        }

        public Criteria andGkNameLessThan(String value) {
            addCriterion("gk_name <", value, "gkName");
            return (Criteria) this;
        }

        public Criteria andGkNameLessThanOrEqualTo(String value) {
            addCriterion("gk_name <=", value, "gkName");
            return (Criteria) this;
        }

        public Criteria andGkNameLike(String value) {
            addCriterion("gk_name like", value, "gkName");
            return (Criteria) this;
        }

        public Criteria andGkNameNotLike(String value) {
            addCriterion("gk_name not like", value, "gkName");
            return (Criteria) this;
        }

        public Criteria andGkNameIn(List<String> values) {
            addCriterion("gk_name in", values, "gkName");
            return (Criteria) this;
        }

        public Criteria andGkNameNotIn(List<String> values) {
            addCriterion("gk_name not in", values, "gkName");
            return (Criteria) this;
        }

        public Criteria andGkNameBetween(String value1, String value2) {
            addCriterion("gk_name between", value1, value2, "gkName");
            return (Criteria) this;
        }

        public Criteria andGkNameNotBetween(String value1, String value2) {
            addCriterion("gk_name not between", value1, value2, "gkName");
            return (Criteria) this;
        }

        public Criteria andGkCommentIsNull() {
            addCriterion("gk_comment is null");
            return (Criteria) this;
        }

        public Criteria andGkCommentIsNotNull() {
            addCriterion("gk_comment is not null");
            return (Criteria) this;
        }

        public Criteria andGkCommentEqualTo(String value) {
            addCriterion("gk_comment =", value, "gkComment");
            return (Criteria) this;
        }

        public Criteria andGkCommentNotEqualTo(String value) {
            addCriterion("gk_comment <>", value, "gkComment");
            return (Criteria) this;
        }

        public Criteria andGkCommentGreaterThan(String value) {
            addCriterion("gk_comment >", value, "gkComment");
            return (Criteria) this;
        }

        public Criteria andGkCommentGreaterThanOrEqualTo(String value) {
            addCriterion("gk_comment >=", value, "gkComment");
            return (Criteria) this;
        }

        public Criteria andGkCommentLessThan(String value) {
            addCriterion("gk_comment <", value, "gkComment");
            return (Criteria) this;
        }

        public Criteria andGkCommentLessThanOrEqualTo(String value) {
            addCriterion("gk_comment <=", value, "gkComment");
            return (Criteria) this;
        }

        public Criteria andGkCommentLike(String value) {
            addCriterion("gk_comment like", value, "gkComment");
            return (Criteria) this;
        }

        public Criteria andGkCommentNotLike(String value) {
            addCriterion("gk_comment not like", value, "gkComment");
            return (Criteria) this;
        }

        public Criteria andGkCommentIn(List<String> values) {
            addCriterion("gk_comment in", values, "gkComment");
            return (Criteria) this;
        }

        public Criteria andGkCommentNotIn(List<String> values) {
            addCriterion("gk_comment not in", values, "gkComment");
            return (Criteria) this;
        }

        public Criteria andGkCommentBetween(String value1, String value2) {
            addCriterion("gk_comment between", value1, value2, "gkComment");
            return (Criteria) this;
        }

        public Criteria andGkCommentNotBetween(String value1, String value2) {
            addCriterion("gk_comment not between", value1, value2, "gkComment");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table good_kind
     *
     * @mbggenerated do_not_delete_during_merge Sun Aug 06 09:44:18 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table good_kind
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}