package com.mysupermarket.pojo;

public class Indent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.i_id
     *
     * @mbggenerated Sat Aug 12 21:19:47 CST 2017
     */
    private Integer iId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.i_useraccount
     *
     * @mbggenerated Sat Aug 12 21:19:47 CST 2017
     */
    private Integer iUseraccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.i_receive
     *
     * @mbggenerated Sat Aug 12 21:19:47 CST 2017
     */
    private Integer iReceive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.i_good
     *
     * @mbggenerated Sat Aug 12 21:19:47 CST 2017
     */
    private Integer iGood;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.i_goodchoose
     *
     * @mbggenerated Sat Aug 12 21:19:47 CST 2017
     */
    private String iGoodchoose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.i_goodnum
     *
     * @mbggenerated Sat Aug 12 21:19:47 CST 2017
     */
    private Integer iGoodnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.i_take
     *
     * @mbggenerated Sat Aug 12 21:19:47 CST 2017
     */
    private Double iTake;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.i_payaccount
     *
     * @mbggenerated Sat Aug 12 21:19:47 CST 2017
     */
    private Integer iPayaccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.i_date
     *
     * @mbggenerated Sat Aug 12 21:19:47 CST 2017
     */
    private String iDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.i_comment
     *
     * @mbggenerated Sat Aug 12 21:19:47 CST 2017
     */
    private String iComment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.i_id
     *
     * @return the value of indent.i_id
     *
     * @mbggenerated Sat Aug 12 21:19:47 CST 2017
     */
    public Integer getiId() {
        return iId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.i_id
     *
     * @param iId the value for indent.i_id
     *
     * @mbggenerated Sat Aug 12 21:19:47 CST 2017
     */
    public void setiId(Integer iId) {
        this.iId = iId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.i_useraccount
     *
     * @return the value of indent.i_useraccount
     *
     * @mbggenerated Sat Aug 12 21:19:47 CST 2017
     */
    public Integer getiUseraccount() {
        return iUseraccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.i_useraccount
     *
     * @param iUseraccount the value for indent.i_useraccount
     *
     * @mbggenerated Sat Aug 12 21:19:47 CST 2017
     */
    public void setiUseraccount(Integer iUseraccount) {
        this.iUseraccount = iUseraccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.i_receive
     *
     * @return the value of indent.i_receive
     *
     * @mbggenerated Sat Aug 12 21:19:47 CST 2017
     */
    public Integer getiReceive() {
        return iReceive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.i_receive
     *
     * @param iReceive the value for indent.i_receive
     *
     * @mbggenerated Sat Aug 12 21:19:47 CST 2017
     */
    public void setiReceive(Integer iReceive) {
        this.iReceive = iReceive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.i_good
     *
     * @return the value of indent.i_good
     *
     * @mbggenerated Sat Aug 12 21:19:47 CST 2017
     */
    public Integer getiGood() {
        return iGood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.i_good
     *
     * @param iGood the value for indent.i_good
     *
     * @mbggenerated Sat Aug 12 21:19:47 CST 2017
     */
    public void setiGood(Integer iGood) {
        this.iGood = iGood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.i_goodchoose
     *
     * @return the value of indent.i_goodchoose
     *
     * @mbggenerated Sat Aug 12 21:19:47 CST 2017
     */
    public String getiGoodchoose() {
        return iGoodchoose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.i_goodchoose
     *
     * @param iGoodchoose the value for indent.i_goodchoose
     *
     * @mbggenerated Sat Aug 12 21:19:47 CST 2017
     */
    public void setiGoodchoose(String iGoodchoose) {
        this.iGoodchoose = iGoodchoose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.i_goodnum
     *
     * @return the value of indent.i_goodnum
     *
     * @mbggenerated Sat Aug 12 21:19:47 CST 2017
     */
    public Integer getiGoodnum() {
        return iGoodnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.i_goodnum
     *
     * @param iGoodnum the value for indent.i_goodnum
     *
     * @mbggenerated Sat Aug 12 21:19:47 CST 2017
     */
    public void setiGoodnum(Integer iGoodnum) {
        this.iGoodnum = iGoodnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.i_take
     *
     * @return the value of indent.i_take
     *
     * @mbggenerated Sat Aug 12 21:19:47 CST 2017
     */
    public Double getiTake() {
        return iTake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.i_take
     *
     * @param iTake the value for indent.i_take
     *
     * @mbggenerated Sat Aug 12 21:19:47 CST 2017
     */
    public void setiTake(Double iTake) {
        this.iTake = iTake;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.i_payaccount
     *
     * @return the value of indent.i_payaccount
     *
     * @mbggenerated Sat Aug 12 21:19:47 CST 2017
     */
    public Integer getiPayaccount() {
        return iPayaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.i_payaccount
     *
     * @param iPayaccount the value for indent.i_payaccount
     *
     * @mbggenerated Sat Aug 12 21:19:47 CST 2017
     */
    public void setiPayaccount(Integer iPayaccount) {
        this.iPayaccount = iPayaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.i_date
     *
     * @return the value of indent.i_date
     *
     * @mbggenerated Sat Aug 12 21:19:47 CST 2017
     */
    public String getiDate() {
        return iDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.i_date
     *
     * @param iDate the value for indent.i_date
     *
     * @mbggenerated Sat Aug 12 21:19:47 CST 2017
     */
    public void setiDate(String iDate) {
        this.iDate = iDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.i_comment
     *
     * @return the value of indent.i_comment
     *
     * @mbggenerated Sat Aug 12 21:19:47 CST 2017
     */
    public String getiComment() {
        return iComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.i_comment
     *
     * @param iComment the value for indent.i_comment
     *
     * @mbggenerated Sat Aug 12 21:19:47 CST 2017
     */
    public void setiComment(String iComment) {
        this.iComment = iComment;
    }
}