package com.mysupermarket.pojo;

import java.util.ArrayList;
import java.util.List;

public class PayAccountExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pay_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pay_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pay_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public PayAccountExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pay_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPAccountIsNull() {
            addCriterion("p_account is null");
            return (Criteria) this;
        }

        public Criteria andPAccountIsNotNull() {
            addCriterion("p_account is not null");
            return (Criteria) this;
        }

        public Criteria andPAccountEqualTo(Integer value) {
            addCriterion("p_account =", value, "pAccount");
            return (Criteria) this;
        }

        public Criteria andPAccountNotEqualTo(Integer value) {
            addCriterion("p_account <>", value, "pAccount");
            return (Criteria) this;
        }

        public Criteria andPAccountGreaterThan(Integer value) {
            addCriterion("p_account >", value, "pAccount");
            return (Criteria) this;
        }

        public Criteria andPAccountGreaterThanOrEqualTo(Integer value) {
            addCriterion("p_account >=", value, "pAccount");
            return (Criteria) this;
        }

        public Criteria andPAccountLessThan(Integer value) {
            addCriterion("p_account <", value, "pAccount");
            return (Criteria) this;
        }

        public Criteria andPAccountLessThanOrEqualTo(Integer value) {
            addCriterion("p_account <=", value, "pAccount");
            return (Criteria) this;
        }

        public Criteria andPAccountIn(List<Integer> values) {
            addCriterion("p_account in", values, "pAccount");
            return (Criteria) this;
        }

        public Criteria andPAccountNotIn(List<Integer> values) {
            addCriterion("p_account not in", values, "pAccount");
            return (Criteria) this;
        }

        public Criteria andPAccountBetween(Integer value1, Integer value2) {
            addCriterion("p_account between", value1, value2, "pAccount");
            return (Criteria) this;
        }

        public Criteria andPAccountNotBetween(Integer value1, Integer value2) {
            addCriterion("p_account not between", value1, value2, "pAccount");
            return (Criteria) this;
        }

        public Criteria andPPasswordIsNull() {
            addCriterion("p_password is null");
            return (Criteria) this;
        }

        public Criteria andPPasswordIsNotNull() {
            addCriterion("p_password is not null");
            return (Criteria) this;
        }

        public Criteria andPPasswordEqualTo(String value) {
            addCriterion("p_password =", value, "pPassword");
            return (Criteria) this;
        }

        public Criteria andPPasswordNotEqualTo(String value) {
            addCriterion("p_password <>", value, "pPassword");
            return (Criteria) this;
        }

        public Criteria andPPasswordGreaterThan(String value) {
            addCriterion("p_password >", value, "pPassword");
            return (Criteria) this;
        }

        public Criteria andPPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("p_password >=", value, "pPassword");
            return (Criteria) this;
        }

        public Criteria andPPasswordLessThan(String value) {
            addCriterion("p_password <", value, "pPassword");
            return (Criteria) this;
        }

        public Criteria andPPasswordLessThanOrEqualTo(String value) {
            addCriterion("p_password <=", value, "pPassword");
            return (Criteria) this;
        }

        public Criteria andPPasswordLike(String value) {
            addCriterion("p_password like", value, "pPassword");
            return (Criteria) this;
        }

        public Criteria andPPasswordNotLike(String value) {
            addCriterion("p_password not like", value, "pPassword");
            return (Criteria) this;
        }

        public Criteria andPPasswordIn(List<String> values) {
            addCriterion("p_password in", values, "pPassword");
            return (Criteria) this;
        }

        public Criteria andPPasswordNotIn(List<String> values) {
            addCriterion("p_password not in", values, "pPassword");
            return (Criteria) this;
        }

        public Criteria andPPasswordBetween(String value1, String value2) {
            addCriterion("p_password between", value1, value2, "pPassword");
            return (Criteria) this;
        }

        public Criteria andPPasswordNotBetween(String value1, String value2) {
            addCriterion("p_password not between", value1, value2, "pPassword");
            return (Criteria) this;
        }

        public Criteria andPPaypasswordIsNull() {
            addCriterion("p_paypassword is null");
            return (Criteria) this;
        }

        public Criteria andPPaypasswordIsNotNull() {
            addCriterion("p_paypassword is not null");
            return (Criteria) this;
        }

        public Criteria andPPaypasswordEqualTo(Integer value) {
            addCriterion("p_paypassword =", value, "pPaypassword");
            return (Criteria) this;
        }

        public Criteria andPPaypasswordNotEqualTo(Integer value) {
            addCriterion("p_paypassword <>", value, "pPaypassword");
            return (Criteria) this;
        }

        public Criteria andPPaypasswordGreaterThan(Integer value) {
            addCriterion("p_paypassword >", value, "pPaypassword");
            return (Criteria) this;
        }

        public Criteria andPPaypasswordGreaterThanOrEqualTo(Integer value) {
            addCriterion("p_paypassword >=", value, "pPaypassword");
            return (Criteria) this;
        }

        public Criteria andPPaypasswordLessThan(Integer value) {
            addCriterion("p_paypassword <", value, "pPaypassword");
            return (Criteria) this;
        }

        public Criteria andPPaypasswordLessThanOrEqualTo(Integer value) {
            addCriterion("p_paypassword <=", value, "pPaypassword");
            return (Criteria) this;
        }

        public Criteria andPPaypasswordIn(List<Integer> values) {
            addCriterion("p_paypassword in", values, "pPaypassword");
            return (Criteria) this;
        }

        public Criteria andPPaypasswordNotIn(List<Integer> values) {
            addCriterion("p_paypassword not in", values, "pPaypassword");
            return (Criteria) this;
        }

        public Criteria andPPaypasswordBetween(Integer value1, Integer value2) {
            addCriterion("p_paypassword between", value1, value2, "pPaypassword");
            return (Criteria) this;
        }

        public Criteria andPPaypasswordNotBetween(Integer value1, Integer value2) {
            addCriterion("p_paypassword not between", value1, value2, "pPaypassword");
            return (Criteria) this;
        }

        public Criteria andPSumMoneyIsNull() {
            addCriterion("p_sum_money is null");
            return (Criteria) this;
        }

        public Criteria andPSumMoneyIsNotNull() {
            addCriterion("p_sum_money is not null");
            return (Criteria) this;
        }

        public Criteria andPSumMoneyEqualTo(Double value) {
            addCriterion("p_sum_money =", value, "pSumMoney");
            return (Criteria) this;
        }

        public Criteria andPSumMoneyNotEqualTo(Double value) {
            addCriterion("p_sum_money <>", value, "pSumMoney");
            return (Criteria) this;
        }

        public Criteria andPSumMoneyGreaterThan(Double value) {
            addCriterion("p_sum_money >", value, "pSumMoney");
            return (Criteria) this;
        }

        public Criteria andPSumMoneyGreaterThanOrEqualTo(Double value) {
            addCriterion("p_sum_money >=", value, "pSumMoney");
            return (Criteria) this;
        }

        public Criteria andPSumMoneyLessThan(Double value) {
            addCriterion("p_sum_money <", value, "pSumMoney");
            return (Criteria) this;
        }

        public Criteria andPSumMoneyLessThanOrEqualTo(Double value) {
            addCriterion("p_sum_money <=", value, "pSumMoney");
            return (Criteria) this;
        }

        public Criteria andPSumMoneyIn(List<Double> values) {
            addCriterion("p_sum_money in", values, "pSumMoney");
            return (Criteria) this;
        }

        public Criteria andPSumMoneyNotIn(List<Double> values) {
            addCriterion("p_sum_money not in", values, "pSumMoney");
            return (Criteria) this;
        }

        public Criteria andPSumMoneyBetween(Double value1, Double value2) {
            addCriterion("p_sum_money between", value1, value2, "pSumMoney");
            return (Criteria) this;
        }

        public Criteria andPSumMoneyNotBetween(Double value1, Double value2) {
            addCriterion("p_sum_money not between", value1, value2, "pSumMoney");
            return (Criteria) this;
        }

        public Criteria andPStatusIsNull() {
            addCriterion("p_status is null");
            return (Criteria) this;
        }

        public Criteria andPStatusIsNotNull() {
            addCriterion("p_status is not null");
            return (Criteria) this;
        }

        public Criteria andPStatusEqualTo(String value) {
            addCriterion("p_status =", value, "pStatus");
            return (Criteria) this;
        }

        public Criteria andPStatusNotEqualTo(String value) {
            addCriterion("p_status <>", value, "pStatus");
            return (Criteria) this;
        }

        public Criteria andPStatusGreaterThan(String value) {
            addCriterion("p_status >", value, "pStatus");
            return (Criteria) this;
        }

        public Criteria andPStatusGreaterThanOrEqualTo(String value) {
            addCriterion("p_status >=", value, "pStatus");
            return (Criteria) this;
        }

        public Criteria andPStatusLessThan(String value) {
            addCriterion("p_status <", value, "pStatus");
            return (Criteria) this;
        }

        public Criteria andPStatusLessThanOrEqualTo(String value) {
            addCriterion("p_status <=", value, "pStatus");
            return (Criteria) this;
        }

        public Criteria andPStatusLike(String value) {
            addCriterion("p_status like", value, "pStatus");
            return (Criteria) this;
        }

        public Criteria andPStatusNotLike(String value) {
            addCriterion("p_status not like", value, "pStatus");
            return (Criteria) this;
        }

        public Criteria andPStatusIn(List<String> values) {
            addCriterion("p_status in", values, "pStatus");
            return (Criteria) this;
        }

        public Criteria andPStatusNotIn(List<String> values) {
            addCriterion("p_status not in", values, "pStatus");
            return (Criteria) this;
        }

        public Criteria andPStatusBetween(String value1, String value2) {
            addCriterion("p_status between", value1, value2, "pStatus");
            return (Criteria) this;
        }

        public Criteria andPStatusNotBetween(String value1, String value2) {
            addCriterion("p_status not between", value1, value2, "pStatus");
            return (Criteria) this;
        }

        public Criteria andPUseraccountIsNull() {
            addCriterion("p_useraccount is null");
            return (Criteria) this;
        }

        public Criteria andPUseraccountIsNotNull() {
            addCriterion("p_useraccount is not null");
            return (Criteria) this;
        }

        public Criteria andPUseraccountEqualTo(Integer value) {
            addCriterion("p_useraccount =", value, "pUseraccount");
            return (Criteria) this;
        }

        public Criteria andPUseraccountNotEqualTo(Integer value) {
            addCriterion("p_useraccount <>", value, "pUseraccount");
            return (Criteria) this;
        }

        public Criteria andPUseraccountGreaterThan(Integer value) {
            addCriterion("p_useraccount >", value, "pUseraccount");
            return (Criteria) this;
        }

        public Criteria andPUseraccountGreaterThanOrEqualTo(Integer value) {
            addCriterion("p_useraccount >=", value, "pUseraccount");
            return (Criteria) this;
        }

        public Criteria andPUseraccountLessThan(Integer value) {
            addCriterion("p_useraccount <", value, "pUseraccount");
            return (Criteria) this;
        }

        public Criteria andPUseraccountLessThanOrEqualTo(Integer value) {
            addCriterion("p_useraccount <=", value, "pUseraccount");
            return (Criteria) this;
        }

        public Criteria andPUseraccountIn(List<Integer> values) {
            addCriterion("p_useraccount in", values, "pUseraccount");
            return (Criteria) this;
        }

        public Criteria andPUseraccountNotIn(List<Integer> values) {
            addCriterion("p_useraccount not in", values, "pUseraccount");
            return (Criteria) this;
        }

        public Criteria andPUseraccountBetween(Integer value1, Integer value2) {
            addCriterion("p_useraccount between", value1, value2, "pUseraccount");
            return (Criteria) this;
        }

        public Criteria andPUseraccountNotBetween(Integer value1, Integer value2) {
            addCriterion("p_useraccount not between", value1, value2, "pUseraccount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pay_account
     *
     * @mbggenerated do_not_delete_during_merge Sun Aug 06 09:44:18 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pay_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}