package com.mysupermarket.pojo;

public class PayAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account.p_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private Integer pAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account.p_password
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private String pPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account.p_paypassword
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private Integer pPaypassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account.p_sum_money
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private Double pSumMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account.p_status
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private String pStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_account.p_useraccount
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private Integer pUseraccount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account.p_account
     *
     * @return the value of pay_account.p_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public Integer getpAccount() {
        return pAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account.p_account
     *
     * @param pAccount the value for pay_account.p_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setpAccount(Integer pAccount) {
        this.pAccount = pAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account.p_password
     *
     * @return the value of pay_account.p_password
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public String getpPassword() {
        return pPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account.p_password
     *
     * @param pPassword the value for pay_account.p_password
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setpPassword(String pPassword) {
        this.pPassword = pPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account.p_paypassword
     *
     * @return the value of pay_account.p_paypassword
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public Integer getpPaypassword() {
        return pPaypassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account.p_paypassword
     *
     * @param pPaypassword the value for pay_account.p_paypassword
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setpPaypassword(Integer pPaypassword) {
        this.pPaypassword = pPaypassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account.p_sum_money
     *
     * @return the value of pay_account.p_sum_money
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public Double getpSumMoney() {
        return pSumMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account.p_sum_money
     *
     * @param pSumMoney the value for pay_account.p_sum_money
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setpSumMoney(Double pSumMoney) {
        this.pSumMoney = pSumMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account.p_status
     *
     * @return the value of pay_account.p_status
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public String getpStatus() {
        return pStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account.p_status
     *
     * @param pStatus the value for pay_account.p_status
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setpStatus(String pStatus) {
        this.pStatus = pStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_account.p_useraccount
     *
     * @return the value of pay_account.p_useraccount
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public Integer getpUseraccount() {
        return pUseraccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_account.p_useraccount
     *
     * @param pUseraccount the value for pay_account.p_useraccount
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setpUseraccount(Integer pUseraccount) {
        this.pUseraccount = pUseraccount;
    }
}