package com.mysupermarket.pojo;

public class ReceiveInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive_info.r_id
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private Integer rId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive_info.r_name
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private String rName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive_info.r_phone
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private Integer rPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive_info.r_address
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private String rAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receive_info.r_useraccount
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private Integer rUseraccount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_info.r_id
     *
     * @return the value of receive_info.r_id
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public Integer getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_info.r_id
     *
     * @param rId the value for receive_info.r_id
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setrId(Integer rId) {
        this.rId = rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_info.r_name
     *
     * @return the value of receive_info.r_name
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public String getrName() {
        return rName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_info.r_name
     *
     * @param rName the value for receive_info.r_name
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setrName(String rName) {
        this.rName = rName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_info.r_phone
     *
     * @return the value of receive_info.r_phone
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public Integer getrPhone() {
        return rPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_info.r_phone
     *
     * @param rPhone the value for receive_info.r_phone
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setrPhone(Integer rPhone) {
        this.rPhone = rPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_info.r_address
     *
     * @return the value of receive_info.r_address
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public String getrAddress() {
        return rAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_info.r_address
     *
     * @param rAddress the value for receive_info.r_address
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setrAddress(String rAddress) {
        this.rAddress = rAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column receive_info.r_useraccount
     *
     * @return the value of receive_info.r_useraccount
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public Integer getrUseraccount() {
        return rUseraccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column receive_info.r_useraccount
     *
     * @param rUseraccount the value for receive_info.r_useraccount
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setrUseraccount(Integer rUseraccount) {
        this.rUseraccount = rUseraccount;
    }
}