package com.mysupermarket.pojo;

import java.util.ArrayList;
import java.util.List;

public class RecordPayAccountExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table record_pay_account
     *
     * @mbggenerated Sun Aug 13 09:07:44 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table record_pay_account
     *
     * @mbggenerated Sun Aug 13 09:07:44 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table record_pay_account
     *
     * @mbggenerated Sun Aug 13 09:07:44 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_pay_account
     *
     * @mbggenerated Sun Aug 13 09:07:44 CST 2017
     */
    public RecordPayAccountExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_pay_account
     *
     * @mbggenerated Sun Aug 13 09:07:44 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_pay_account
     *
     * @mbggenerated Sun Aug 13 09:07:44 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_pay_account
     *
     * @mbggenerated Sun Aug 13 09:07:44 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_pay_account
     *
     * @mbggenerated Sun Aug 13 09:07:44 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_pay_account
     *
     * @mbggenerated Sun Aug 13 09:07:44 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_pay_account
     *
     * @mbggenerated Sun Aug 13 09:07:44 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_pay_account
     *
     * @mbggenerated Sun Aug 13 09:07:44 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_pay_account
     *
     * @mbggenerated Sun Aug 13 09:07:44 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_pay_account
     *
     * @mbggenerated Sun Aug 13 09:07:44 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_pay_account
     *
     * @mbggenerated Sun Aug 13 09:07:44 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table record_pay_account
     *
     * @mbggenerated Sun Aug 13 09:07:44 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRpaIdIsNull() {
            addCriterion("rpa_id is null");
            return (Criteria) this;
        }

        public Criteria andRpaIdIsNotNull() {
            addCriterion("rpa_id is not null");
            return (Criteria) this;
        }

        public Criteria andRpaIdEqualTo(Integer value) {
            addCriterion("rpa_id =", value, "rpaId");
            return (Criteria) this;
        }

        public Criteria andRpaIdNotEqualTo(Integer value) {
            addCriterion("rpa_id <>", value, "rpaId");
            return (Criteria) this;
        }

        public Criteria andRpaIdGreaterThan(Integer value) {
            addCriterion("rpa_id >", value, "rpaId");
            return (Criteria) this;
        }

        public Criteria andRpaIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("rpa_id >=", value, "rpaId");
            return (Criteria) this;
        }

        public Criteria andRpaIdLessThan(Integer value) {
            addCriterion("rpa_id <", value, "rpaId");
            return (Criteria) this;
        }

        public Criteria andRpaIdLessThanOrEqualTo(Integer value) {
            addCriterion("rpa_id <=", value, "rpaId");
            return (Criteria) this;
        }

        public Criteria andRpaIdIn(List<Integer> values) {
            addCriterion("rpa_id in", values, "rpaId");
            return (Criteria) this;
        }

        public Criteria andRpaIdNotIn(List<Integer> values) {
            addCriterion("rpa_id not in", values, "rpaId");
            return (Criteria) this;
        }

        public Criteria andRpaIdBetween(Integer value1, Integer value2) {
            addCriterion("rpa_id between", value1, value2, "rpaId");
            return (Criteria) this;
        }

        public Criteria andRpaIdNotBetween(Integer value1, Integer value2) {
            addCriterion("rpa_id not between", value1, value2, "rpaId");
            return (Criteria) this;
        }

        public Criteria andRpaMoneyIsNull() {
            addCriterion("rpa_money is null");
            return (Criteria) this;
        }

        public Criteria andRpaMoneyIsNotNull() {
            addCriterion("rpa_money is not null");
            return (Criteria) this;
        }

        public Criteria andRpaMoneyEqualTo(Double value) {
            addCriterion("rpa_money =", value, "rpaMoney");
            return (Criteria) this;
        }

        public Criteria andRpaMoneyNotEqualTo(Double value) {
            addCriterion("rpa_money <>", value, "rpaMoney");
            return (Criteria) this;
        }

        public Criteria andRpaMoneyGreaterThan(Double value) {
            addCriterion("rpa_money >", value, "rpaMoney");
            return (Criteria) this;
        }

        public Criteria andRpaMoneyGreaterThanOrEqualTo(Double value) {
            addCriterion("rpa_money >=", value, "rpaMoney");
            return (Criteria) this;
        }

        public Criteria andRpaMoneyLessThan(Double value) {
            addCriterion("rpa_money <", value, "rpaMoney");
            return (Criteria) this;
        }

        public Criteria andRpaMoneyLessThanOrEqualTo(Double value) {
            addCriterion("rpa_money <=", value, "rpaMoney");
            return (Criteria) this;
        }

        public Criteria andRpaMoneyIn(List<Double> values) {
            addCriterion("rpa_money in", values, "rpaMoney");
            return (Criteria) this;
        }

        public Criteria andRpaMoneyNotIn(List<Double> values) {
            addCriterion("rpa_money not in", values, "rpaMoney");
            return (Criteria) this;
        }

        public Criteria andRpaMoneyBetween(Double value1, Double value2) {
            addCriterion("rpa_money between", value1, value2, "rpaMoney");
            return (Criteria) this;
        }

        public Criteria andRpaMoneyNotBetween(Double value1, Double value2) {
            addCriterion("rpa_money not between", value1, value2, "rpaMoney");
            return (Criteria) this;
        }

        public Criteria andRpaKindIsNull() {
            addCriterion("rpa_kind is null");
            return (Criteria) this;
        }

        public Criteria andRpaKindIsNotNull() {
            addCriterion("rpa_kind is not null");
            return (Criteria) this;
        }

        public Criteria andRpaKindEqualTo(String value) {
            addCriterion("rpa_kind =", value, "rpaKind");
            return (Criteria) this;
        }

        public Criteria andRpaKindNotEqualTo(String value) {
            addCriterion("rpa_kind <>", value, "rpaKind");
            return (Criteria) this;
        }

        public Criteria andRpaKindGreaterThan(String value) {
            addCriterion("rpa_kind >", value, "rpaKind");
            return (Criteria) this;
        }

        public Criteria andRpaKindGreaterThanOrEqualTo(String value) {
            addCriterion("rpa_kind >=", value, "rpaKind");
            return (Criteria) this;
        }

        public Criteria andRpaKindLessThan(String value) {
            addCriterion("rpa_kind <", value, "rpaKind");
            return (Criteria) this;
        }

        public Criteria andRpaKindLessThanOrEqualTo(String value) {
            addCriterion("rpa_kind <=", value, "rpaKind");
            return (Criteria) this;
        }

        public Criteria andRpaKindLike(String value) {
            addCriterion("rpa_kind like", value, "rpaKind");
            return (Criteria) this;
        }

        public Criteria andRpaKindNotLike(String value) {
            addCriterion("rpa_kind not like", value, "rpaKind");
            return (Criteria) this;
        }

        public Criteria andRpaKindIn(List<String> values) {
            addCriterion("rpa_kind in", values, "rpaKind");
            return (Criteria) this;
        }

        public Criteria andRpaKindNotIn(List<String> values) {
            addCriterion("rpa_kind not in", values, "rpaKind");
            return (Criteria) this;
        }

        public Criteria andRpaKindBetween(String value1, String value2) {
            addCriterion("rpa_kind between", value1, value2, "rpaKind");
            return (Criteria) this;
        }

        public Criteria andRpaKindNotBetween(String value1, String value2) {
            addCriterion("rpa_kind not between", value1, value2, "rpaKind");
            return (Criteria) this;
        }

        public Criteria andRpaDateIsNull() {
            addCriterion("rpa_date is null");
            return (Criteria) this;
        }

        public Criteria andRpaDateIsNotNull() {
            addCriterion("rpa_date is not null");
            return (Criteria) this;
        }

        public Criteria andRpaDateEqualTo(String value) {
            addCriterion("rpa_date =", value, "rpaDate");
            return (Criteria) this;
        }

        public Criteria andRpaDateNotEqualTo(String value) {
            addCriterion("rpa_date <>", value, "rpaDate");
            return (Criteria) this;
        }

        public Criteria andRpaDateGreaterThan(String value) {
            addCriterion("rpa_date >", value, "rpaDate");
            return (Criteria) this;
        }

        public Criteria andRpaDateGreaterThanOrEqualTo(String value) {
            addCriterion("rpa_date >=", value, "rpaDate");
            return (Criteria) this;
        }

        public Criteria andRpaDateLessThan(String value) {
            addCriterion("rpa_date <", value, "rpaDate");
            return (Criteria) this;
        }

        public Criteria andRpaDateLessThanOrEqualTo(String value) {
            addCriterion("rpa_date <=", value, "rpaDate");
            return (Criteria) this;
        }

        public Criteria andRpaDateLike(String value) {
            addCriterion("rpa_date like", value, "rpaDate");
            return (Criteria) this;
        }

        public Criteria andRpaDateNotLike(String value) {
            addCriterion("rpa_date not like", value, "rpaDate");
            return (Criteria) this;
        }

        public Criteria andRpaDateIn(List<String> values) {
            addCriterion("rpa_date in", values, "rpaDate");
            return (Criteria) this;
        }

        public Criteria andRpaDateNotIn(List<String> values) {
            addCriterion("rpa_date not in", values, "rpaDate");
            return (Criteria) this;
        }

        public Criteria andRpaDateBetween(String value1, String value2) {
            addCriterion("rpa_date between", value1, value2, "rpaDate");
            return (Criteria) this;
        }

        public Criteria andRpaDateNotBetween(String value1, String value2) {
            addCriterion("rpa_date not between", value1, value2, "rpaDate");
            return (Criteria) this;
        }

        public Criteria andRpaPayaccountIsNull() {
            addCriterion("rpa_payaccount is null");
            return (Criteria) this;
        }

        public Criteria andRpaPayaccountIsNotNull() {
            addCriterion("rpa_payaccount is not null");
            return (Criteria) this;
        }

        public Criteria andRpaPayaccountEqualTo(Integer value) {
            addCriterion("rpa_payaccount =", value, "rpaPayaccount");
            return (Criteria) this;
        }

        public Criteria andRpaPayaccountNotEqualTo(Integer value) {
            addCriterion("rpa_payaccount <>", value, "rpaPayaccount");
            return (Criteria) this;
        }

        public Criteria andRpaPayaccountGreaterThan(Integer value) {
            addCriterion("rpa_payaccount >", value, "rpaPayaccount");
            return (Criteria) this;
        }

        public Criteria andRpaPayaccountGreaterThanOrEqualTo(Integer value) {
            addCriterion("rpa_payaccount >=", value, "rpaPayaccount");
            return (Criteria) this;
        }

        public Criteria andRpaPayaccountLessThan(Integer value) {
            addCriterion("rpa_payaccount <", value, "rpaPayaccount");
            return (Criteria) this;
        }

        public Criteria andRpaPayaccountLessThanOrEqualTo(Integer value) {
            addCriterion("rpa_payaccount <=", value, "rpaPayaccount");
            return (Criteria) this;
        }

        public Criteria andRpaPayaccountIn(List<Integer> values) {
            addCriterion("rpa_payaccount in", values, "rpaPayaccount");
            return (Criteria) this;
        }

        public Criteria andRpaPayaccountNotIn(List<Integer> values) {
            addCriterion("rpa_payaccount not in", values, "rpaPayaccount");
            return (Criteria) this;
        }

        public Criteria andRpaPayaccountBetween(Integer value1, Integer value2) {
            addCriterion("rpa_payaccount between", value1, value2, "rpaPayaccount");
            return (Criteria) this;
        }

        public Criteria andRpaPayaccountNotBetween(Integer value1, Integer value2) {
            addCriterion("rpa_payaccount not between", value1, value2, "rpaPayaccount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table record_pay_account
     *
     * @mbggenerated do_not_delete_during_merge Sun Aug 13 09:07:44 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table record_pay_account
     *
     * @mbggenerated Sun Aug 13 09:07:44 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}