package com.mysupermarket.pojo;

public class RecordPayAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_pay_account.rpa_id
     *
     * @mbggenerated Sun Aug 13 09:07:44 CST 2017
     */
    private Integer rpaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_pay_account.rpa_money
     *
     * @mbggenerated Sun Aug 13 09:07:44 CST 2017
     */
    private Double rpaMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_pay_account.rpa_kind
     *
     * @mbggenerated Sun Aug 13 09:07:44 CST 2017
     */
    private String rpaKind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_pay_account.rpa_date
     *
     * @mbggenerated Sun Aug 13 09:07:44 CST 2017
     */
    private String rpaDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record_pay_account.rpa_payaccount
     *
     * @mbggenerated Sun Aug 13 09:07:44 CST 2017
     */
    private Integer rpaPayaccount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_pay_account.rpa_id
     *
     * @return the value of record_pay_account.rpa_id
     *
     * @mbggenerated Sun Aug 13 09:07:44 CST 2017
     */
    public Integer getRpaId() {
        return rpaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_pay_account.rpa_id
     *
     * @param rpaId the value for record_pay_account.rpa_id
     *
     * @mbggenerated Sun Aug 13 09:07:44 CST 2017
     */
    public void setRpaId(Integer rpaId) {
        this.rpaId = rpaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_pay_account.rpa_money
     *
     * @return the value of record_pay_account.rpa_money
     *
     * @mbggenerated Sun Aug 13 09:07:44 CST 2017
     */
    public Double getRpaMoney() {
        return rpaMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_pay_account.rpa_money
     *
     * @param rpaMoney the value for record_pay_account.rpa_money
     *
     * @mbggenerated Sun Aug 13 09:07:44 CST 2017
     */
    public void setRpaMoney(Double rpaMoney) {
        this.rpaMoney = rpaMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_pay_account.rpa_kind
     *
     * @return the value of record_pay_account.rpa_kind
     *
     * @mbggenerated Sun Aug 13 09:07:44 CST 2017
     */
    public String getRpaKind() {
        return rpaKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_pay_account.rpa_kind
     *
     * @param rpaKind the value for record_pay_account.rpa_kind
     *
     * @mbggenerated Sun Aug 13 09:07:44 CST 2017
     */
    public void setRpaKind(String rpaKind) {
        this.rpaKind = rpaKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_pay_account.rpa_date
     *
     * @return the value of record_pay_account.rpa_date
     *
     * @mbggenerated Sun Aug 13 09:07:44 CST 2017
     */
    public String getRpaDate() {
        return rpaDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_pay_account.rpa_date
     *
     * @param rpaDate the value for record_pay_account.rpa_date
     *
     * @mbggenerated Sun Aug 13 09:07:44 CST 2017
     */
    public void setRpaDate(String rpaDate) {
        this.rpaDate = rpaDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record_pay_account.rpa_payaccount
     *
     * @return the value of record_pay_account.rpa_payaccount
     *
     * @mbggenerated Sun Aug 13 09:07:44 CST 2017
     */
    public Integer getRpaPayaccount() {
        return rpaPayaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record_pay_account.rpa_payaccount
     *
     * @param rpaPayaccount the value for record_pay_account.rpa_payaccount
     *
     * @mbggenerated Sun Aug 13 09:07:44 CST 2017
     */
    public void setRpaPayaccount(Integer rpaPayaccount) {
        this.rpaPayaccount = rpaPayaccount;
    }
}