package com.mysupermarket.pojo;

public class ShopAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_account.sp_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private Integer spAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_account.sp_password
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private String spPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_account.sp_name
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private String spName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_account.sp_from
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    private String spFrom;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_account.sp_account
     *
     * @return the value of shop_account.sp_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public Integer getSpAccount() {
        return spAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_account.sp_account
     *
     * @param spAccount the value for shop_account.sp_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setSpAccount(Integer spAccount) {
        this.spAccount = spAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_account.sp_password
     *
     * @return the value of shop_account.sp_password
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public String getSpPassword() {
        return spPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_account.sp_password
     *
     * @param spPassword the value for shop_account.sp_password
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setSpPassword(String spPassword) {
        this.spPassword = spPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_account.sp_name
     *
     * @return the value of shop_account.sp_name
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public String getSpName() {
        return spName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_account.sp_name
     *
     * @param spName the value for shop_account.sp_name
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setSpName(String spName) {
        this.spName = spName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_account.sp_from
     *
     * @return the value of shop_account.sp_from
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public String getSpFrom() {
        return spFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_account.sp_from
     *
     * @param spFrom the value for shop_account.sp_from
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setSpFrom(String spFrom) {
        this.spFrom = spFrom;
    }
}