package com.mysupermarket.pojo;

import java.util.ArrayList;
import java.util.List;

public class ShopAccountExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public ShopAccountExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shop_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSpAccountIsNull() {
            addCriterion("sp_account is null");
            return (Criteria) this;
        }

        public Criteria andSpAccountIsNotNull() {
            addCriterion("sp_account is not null");
            return (Criteria) this;
        }

        public Criteria andSpAccountEqualTo(Integer value) {
            addCriterion("sp_account =", value, "spAccount");
            return (Criteria) this;
        }

        public Criteria andSpAccountNotEqualTo(Integer value) {
            addCriterion("sp_account <>", value, "spAccount");
            return (Criteria) this;
        }

        public Criteria andSpAccountGreaterThan(Integer value) {
            addCriterion("sp_account >", value, "spAccount");
            return (Criteria) this;
        }

        public Criteria andSpAccountGreaterThanOrEqualTo(Integer value) {
            addCriterion("sp_account >=", value, "spAccount");
            return (Criteria) this;
        }

        public Criteria andSpAccountLessThan(Integer value) {
            addCriterion("sp_account <", value, "spAccount");
            return (Criteria) this;
        }

        public Criteria andSpAccountLessThanOrEqualTo(Integer value) {
            addCriterion("sp_account <=", value, "spAccount");
            return (Criteria) this;
        }

        public Criteria andSpAccountIn(List<Integer> values) {
            addCriterion("sp_account in", values, "spAccount");
            return (Criteria) this;
        }

        public Criteria andSpAccountNotIn(List<Integer> values) {
            addCriterion("sp_account not in", values, "spAccount");
            return (Criteria) this;
        }

        public Criteria andSpAccountBetween(Integer value1, Integer value2) {
            addCriterion("sp_account between", value1, value2, "spAccount");
            return (Criteria) this;
        }

        public Criteria andSpAccountNotBetween(Integer value1, Integer value2) {
            addCriterion("sp_account not between", value1, value2, "spAccount");
            return (Criteria) this;
        }

        public Criteria andSpPasswordIsNull() {
            addCriterion("sp_password is null");
            return (Criteria) this;
        }

        public Criteria andSpPasswordIsNotNull() {
            addCriterion("sp_password is not null");
            return (Criteria) this;
        }

        public Criteria andSpPasswordEqualTo(String value) {
            addCriterion("sp_password =", value, "spPassword");
            return (Criteria) this;
        }

        public Criteria andSpPasswordNotEqualTo(String value) {
            addCriterion("sp_password <>", value, "spPassword");
            return (Criteria) this;
        }

        public Criteria andSpPasswordGreaterThan(String value) {
            addCriterion("sp_password >", value, "spPassword");
            return (Criteria) this;
        }

        public Criteria andSpPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("sp_password >=", value, "spPassword");
            return (Criteria) this;
        }

        public Criteria andSpPasswordLessThan(String value) {
            addCriterion("sp_password <", value, "spPassword");
            return (Criteria) this;
        }

        public Criteria andSpPasswordLessThanOrEqualTo(String value) {
            addCriterion("sp_password <=", value, "spPassword");
            return (Criteria) this;
        }

        public Criteria andSpPasswordLike(String value) {
            addCriterion("sp_password like", value, "spPassword");
            return (Criteria) this;
        }

        public Criteria andSpPasswordNotLike(String value) {
            addCriterion("sp_password not like", value, "spPassword");
            return (Criteria) this;
        }

        public Criteria andSpPasswordIn(List<String> values) {
            addCriterion("sp_password in", values, "spPassword");
            return (Criteria) this;
        }

        public Criteria andSpPasswordNotIn(List<String> values) {
            addCriterion("sp_password not in", values, "spPassword");
            return (Criteria) this;
        }

        public Criteria andSpPasswordBetween(String value1, String value2) {
            addCriterion("sp_password between", value1, value2, "spPassword");
            return (Criteria) this;
        }

        public Criteria andSpPasswordNotBetween(String value1, String value2) {
            addCriterion("sp_password not between", value1, value2, "spPassword");
            return (Criteria) this;
        }

        public Criteria andSpNameIsNull() {
            addCriterion("sp_name is null");
            return (Criteria) this;
        }

        public Criteria andSpNameIsNotNull() {
            addCriterion("sp_name is not null");
            return (Criteria) this;
        }

        public Criteria andSpNameEqualTo(String value) {
            addCriterion("sp_name =", value, "spName");
            return (Criteria) this;
        }

        public Criteria andSpNameNotEqualTo(String value) {
            addCriterion("sp_name <>", value, "spName");
            return (Criteria) this;
        }

        public Criteria andSpNameGreaterThan(String value) {
            addCriterion("sp_name >", value, "spName");
            return (Criteria) this;
        }

        public Criteria andSpNameGreaterThanOrEqualTo(String value) {
            addCriterion("sp_name >=", value, "spName");
            return (Criteria) this;
        }

        public Criteria andSpNameLessThan(String value) {
            addCriterion("sp_name <", value, "spName");
            return (Criteria) this;
        }

        public Criteria andSpNameLessThanOrEqualTo(String value) {
            addCriterion("sp_name <=", value, "spName");
            return (Criteria) this;
        }

        public Criteria andSpNameLike(String value) {
            addCriterion("sp_name like", value, "spName");
            return (Criteria) this;
        }

        public Criteria andSpNameNotLike(String value) {
            addCriterion("sp_name not like", value, "spName");
            return (Criteria) this;
        }

        public Criteria andSpNameIn(List<String> values) {
            addCriterion("sp_name in", values, "spName");
            return (Criteria) this;
        }

        public Criteria andSpNameNotIn(List<String> values) {
            addCriterion("sp_name not in", values, "spName");
            return (Criteria) this;
        }

        public Criteria andSpNameBetween(String value1, String value2) {
            addCriterion("sp_name between", value1, value2, "spName");
            return (Criteria) this;
        }

        public Criteria andSpNameNotBetween(String value1, String value2) {
            addCriterion("sp_name not between", value1, value2, "spName");
            return (Criteria) this;
        }

        public Criteria andSpFromIsNull() {
            addCriterion("sp_from is null");
            return (Criteria) this;
        }

        public Criteria andSpFromIsNotNull() {
            addCriterion("sp_from is not null");
            return (Criteria) this;
        }

        public Criteria andSpFromEqualTo(String value) {
            addCriterion("sp_from =", value, "spFrom");
            return (Criteria) this;
        }

        public Criteria andSpFromNotEqualTo(String value) {
            addCriterion("sp_from <>", value, "spFrom");
            return (Criteria) this;
        }

        public Criteria andSpFromGreaterThan(String value) {
            addCriterion("sp_from >", value, "spFrom");
            return (Criteria) this;
        }

        public Criteria andSpFromGreaterThanOrEqualTo(String value) {
            addCriterion("sp_from >=", value, "spFrom");
            return (Criteria) this;
        }

        public Criteria andSpFromLessThan(String value) {
            addCriterion("sp_from <", value, "spFrom");
            return (Criteria) this;
        }

        public Criteria andSpFromLessThanOrEqualTo(String value) {
            addCriterion("sp_from <=", value, "spFrom");
            return (Criteria) this;
        }

        public Criteria andSpFromLike(String value) {
            addCriterion("sp_from like", value, "spFrom");
            return (Criteria) this;
        }

        public Criteria andSpFromNotLike(String value) {
            addCriterion("sp_from not like", value, "spFrom");
            return (Criteria) this;
        }

        public Criteria andSpFromIn(List<String> values) {
            addCriterion("sp_from in", values, "spFrom");
            return (Criteria) this;
        }

        public Criteria andSpFromNotIn(List<String> values) {
            addCriterion("sp_from not in", values, "spFrom");
            return (Criteria) this;
        }

        public Criteria andSpFromBetween(String value1, String value2) {
            addCriterion("sp_from between", value1, value2, "spFrom");
            return (Criteria) this;
        }

        public Criteria andSpFromNotBetween(String value1, String value2) {
            addCriterion("sp_from not between", value1, value2, "spFrom");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shop_account
     *
     * @mbggenerated do_not_delete_during_merge Sun Aug 06 09:44:18 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shop_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}