package com.mysupermarket.mapper;

import com.mysupermarket.pojo.GoodEvaluate;
import com.mysupermarket.pojo.GoodEvaluateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodEvaluateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_evaluate
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int countByExample(GoodEvaluateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_evaluate
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int deleteByExample(GoodEvaluateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_evaluate
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int deleteByPrimaryKey(Integer gdlId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_evaluate
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int insert(GoodEvaluate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_evaluate
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int insertSelective(GoodEvaluate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_evaluate
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    List<GoodEvaluate> selectByExample(GoodEvaluateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_evaluate
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    GoodEvaluate selectByPrimaryKey(Integer gdlId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_evaluate
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int updateByExampleSelective(@Param("record") GoodEvaluate record, @Param("example") GoodEvaluateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_evaluate
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int updateByExample(@Param("record") GoodEvaluate record, @Param("example") GoodEvaluateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_evaluate
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int updateByPrimaryKeySelective(GoodEvaluate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_evaluate
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int updateByPrimaryKey(GoodEvaluate record);
    
    /*
     * 作用 : 根据商品id起始加载id结束id加载商品评论
     * 	param :
     * 		goodid, startid, endid
     * return :
     * 		List<GoodEvaluate> list
     * */
    List<GoodEvaluate> getEvaluateByLastId(@Param("goodid")int goodid, @Param("lastid")int lastid, @Param("loadnum")int loadnum);
    
}