package com.mysupermarket.mapper;

import com.mysupermarket.pojo.GoodBuycar;
import com.mysupermarket.pojo.GoodBuycarExample;
import com.mysupermarket.pojo.GoodBuycarKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodBuycarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_buycar
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int countByExample(GoodBuycarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_buycar
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int deleteByExample(GoodBuycarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_buycar
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int deleteByPrimaryKey(GoodBuycarKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_buycar
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int insert(GoodBuycar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_buycar
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int insertSelective(GoodBuycar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_buycar
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    List<GoodBuycar> selectByExample(GoodBuycarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_buycar
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    GoodBuycar selectByPrimaryKey(GoodBuycarKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_buycar
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int updateByExampleSelective(@Param("record") GoodBuycar record, @Param("example") GoodBuycarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_buycar
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int updateByExample(@Param("record") GoodBuycar record, @Param("example") GoodBuycarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_buycar
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int updateByPrimaryKeySelective(GoodBuycar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_buycar
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int updateByPrimaryKey(GoodBuycar record);
}