package com.mysupermarket.mapper;

import com.mysupermarket.pojo.GoodKind;
import com.mysupermarket.pojo.GoodKindExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodKindMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_kind
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int countByExample(GoodKindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_kind
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int deleteByExample(GoodKindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_kind
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int deleteByPrimaryKey(Integer gkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_kind
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int insert(GoodKind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_kind
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int insertSelective(GoodKind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_kind
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    List<GoodKind> selectByExample(GoodKindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_kind
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    GoodKind selectByPrimaryKey(Integer gkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_kind
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int updateByExampleSelective(@Param("record") GoodKind record, @Param("example") GoodKindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_kind
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int updateByExample(@Param("record") GoodKind record, @Param("example") GoodKindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_kind
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int updateByPrimaryKeySelective(GoodKind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good_kind
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int updateByPrimaryKey(GoodKind record);
}