package com.mysupermarket.mapper;

import com.mysupermarket.pojo.Indent;
import com.mysupermarket.pojo.IndentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IndentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indent
     *
     * @mbggenerated Sat Aug 12 21:19:47 CST 2017
     */
    int countByExample(IndentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indent
     *
     * @mbggenerated Sat Aug 12 21:19:47 CST 2017
     */
    int deleteByExample(IndentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indent
     *
     * @mbggenerated Sat Aug 12 21:19:47 CST 2017
     */
    int deleteByPrimaryKey(Integer iId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indent
     *
     * @mbggenerated Sat Aug 12 21:19:47 CST 2017
     */
    int insert(Indent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indent
     *
     * @mbggenerated Sat Aug 12 21:19:47 CST 2017
     */
    int insertSelective(Indent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indent
     *
     * @mbggenerated Sat Aug 12 21:19:47 CST 2017
     */
    List<Indent> selectByExample(IndentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indent
     *
     * @mbggenerated Sat Aug 12 21:19:47 CST 2017
     */
    Indent selectByPrimaryKey(Integer iId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indent
     *
     * @mbggenerated Sat Aug 12 21:19:47 CST 2017
     */
    int updateByExampleSelective(@Param("record") Indent record, @Param("example") IndentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indent
     *
     * @mbggenerated Sat Aug 12 21:19:47 CST 2017
     */
    int updateByExample(@Param("record") Indent record, @Param("example") IndentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indent
     *
     * @mbggenerated Sat Aug 12 21:19:47 CST 2017
     */
    int updateByPrimaryKeySelective(Indent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table indent
     *
     * @mbggenerated Sat Aug 12 21:19:47 CST 2017
     */
    int updateByPrimaryKey(Indent record);
    
    /*
     * 作用 :
     * 		将提交的订单indent保存到数据库中
     * 	param
     * 		indent
     * 	return
     * 		primarykey
     * */
    int saveIndent(Indent indent);
    
}