package com.mysupermarket.mapper;

import com.mysupermarket.pojo.PayAccount;
import com.mysupermarket.pojo.PayAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PayAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int countByExample(PayAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int deleteByExample(PayAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int deleteByPrimaryKey(Integer pAccount);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int insert(PayAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int insertSelective(PayAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    List<PayAccount> selectByExample(PayAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    PayAccount selectByPrimaryKey(Integer pAccount);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int updateByExampleSelective(@Param("record") PayAccount record, @Param("example") PayAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int updateByExample(@Param("record") PayAccount record, @Param("example") PayAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int updateByPrimaryKeySelective(PayAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int updateByPrimaryKey(PayAccount record);
    
    /*
     * 作用 :
     * 		验证该支付账号是否有效,支付密码是否正确
     * 	param :
     * 		pay_account, pay_password
     * return :
     * 		boolean
     * */
    PayAccount verifyPayAcount(int pay_account);

    /*
     *  作用 :
     *  		根据payaccount更新目前账户余额
     *  param :
     *  		payAccount, pSumMoney
     *  return :
     *  		int
     * */
    int UpdatePayAccount(@Param("payAccount")int payAccount, @Param("pSumMoney")double pSumMoney);
    
    /*
     * 作用 :
     * 		根据传进来的username获取默认本账号的第一个默认支付账号
     * param
     * 		int username
     * return 
     * 		List<PayAccount>
     * */
    List<PayAccount> getByUsername(int username);
    
}