package com.mysupermarket.mapper;

import com.mysupermarket.pojo.ReceiveInfo;
import com.mysupermarket.pojo.ReceiveInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReceiveInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive_info
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int countByExample(ReceiveInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive_info
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int deleteByExample(ReceiveInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive_info
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int deleteByPrimaryKey(Integer rId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive_info
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int insert(ReceiveInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive_info
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int insertSelective(ReceiveInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive_info
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    List<ReceiveInfo> selectByExample(ReceiveInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive_info
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    ReceiveInfo selectByPrimaryKey(Integer rId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive_info
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int updateByExampleSelective(@Param("record") ReceiveInfo record, @Param("example") ReceiveInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive_info
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int updateByExample(@Param("record") ReceiveInfo record, @Param("example") ReceiveInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive_info
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int updateByPrimaryKeySelective(ReceiveInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table receive_info
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int updateByPrimaryKey(ReceiveInfo record);
    
    /*
     * 作用 :
     * 		根据用户的useraccount获取相应的默认收货地址
     * param :
     * 		useraccount
     * return :
     * 		ReceiveInfo
     * 
     * */
    
    ReceiveInfo SelectByUseraccount(int username);
    
    /*
     *  作用 :
     *  		根据name, phone, address获取到收货信息的id
     *   param :
     *   		name, phone, address
     *   return :
     *   		ReceiveInfo
     * */
    ReceiveInfo get(@Param("name")String name, @Param("phone")int phone, @Param("address")String address);
    
}