package com.mysupermarket.mapper;

import com.mysupermarket.pojo.RecordPayAccount;
import com.mysupermarket.pojo.RecordPayAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RecordPayAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_pay_account
     *
     * @mbggenerated Sun Aug 13 09:07:44 CST 2017
     */
    int countByExample(RecordPayAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_pay_account
     *
     * @mbggenerated Sun Aug 13 09:07:44 CST 2017
     */
    int deleteByExample(RecordPayAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_pay_account
     *
     * @mbggenerated Sun Aug 13 09:07:44 CST 2017
     */
    int deleteByPrimaryKey(Integer rpaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_pay_account
     *
     * @mbggenerated Sun Aug 13 09:07:44 CST 2017
     */
    int insert(RecordPayAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_pay_account
     *
     * @mbggenerated Sun Aug 13 09:07:44 CST 2017
     */
    int insertSelective(RecordPayAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_pay_account
     *
     * @mbggenerated Sun Aug 13 09:07:44 CST 2017
     */
    List<RecordPayAccount> selectByExample(RecordPayAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_pay_account
     *
     * @mbggenerated Sun Aug 13 09:07:44 CST 2017
     */
    RecordPayAccount selectByPrimaryKey(Integer rpaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_pay_account
     *
     * @mbggenerated Sun Aug 13 09:07:44 CST 2017
     */
    int updateByExampleSelective(@Param("record") RecordPayAccount record, @Param("example") RecordPayAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_pay_account
     *
     * @mbggenerated Sun Aug 13 09:07:44 CST 2017
     */
    int updateByExample(@Param("record") RecordPayAccount record, @Param("example") RecordPayAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_pay_account
     *
     * @mbggenerated Sun Aug 13 09:07:44 CST 2017
     */
    int updateByPrimaryKeySelective(RecordPayAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record_pay_account
     *
     * @mbggenerated Sun Aug 13 09:07:44 CST 2017
     */
    int updateByPrimaryKey(RecordPayAccount record);
    
    /*
     * 作用 :
     * 		根据传进来的RecordPayAccount 保存到数据库中
     * 	param :
     * 		RecordPayAccount
     * 	return :
     * 		int(记录数)
     * */
    int saveRecordPayAccount(RecordPayAccount recordPayAccount);
    
}