package com.mysupermarket.mapper;

import com.mysupermarket.pojo.ShopAccount;
import com.mysupermarket.pojo.ShopAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int countByExample(ShopAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int deleteByExample(ShopAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int deleteByPrimaryKey(Integer spAccount);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int insert(ShopAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int insertSelective(ShopAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    List<ShopAccount> selectByExample(ShopAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    ShopAccount selectByPrimaryKey(Integer spAccount);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int updateByExampleSelective(@Param("record") ShopAccount record, @Param("example") ShopAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int updateByExample(@Param("record") ShopAccount record, @Param("example") ShopAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int updateByPrimaryKeySelective(ShopAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int updateByPrimaryKey(ShopAccount record);
}