package com.mysupermarket.mapper;

import com.mysupermarket.pojo.UserAccount;
import com.mysupermarket.pojo.UserAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int countByExample(UserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int deleteByExample(UserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int deleteByPrimaryKey(Integer uaUsername);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int insert(UserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int insertSelective(UserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    List<UserAccount> selectByExample(UserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    UserAccount selectByPrimaryKey(Integer uaUsername);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserAccount record, @Param("example") UserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int updateByExample(@Param("record") UserAccount record, @Param("example") UserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int updateByPrimaryKeySelective(UserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account
     *
     * @mbggenerated Sun Aug 06 09:44:18 CST 2017
     */
    int updateByPrimaryKey(UserAccount record);
    
    /*
     * 作用 : 
     * 		根据username获取userAccount
     * param :
     * 		username
     * return
     * 		UserAccount
     * */
   List<UserAccount> getUserAccount(int username);
   
   /*
    * 作用 :
    * 		根据username, email查询是否存在该UserAccount
    * param :
    *		username, email 
    *return :
    *		boolean
    *
    * */
   List<UserAccount> getUserAccountByEmail(@Param("username")int username, @Param("email")String email);
   
   /*
    * 作用 :
    * 		将账号为username的密码修改为newpassword
    * param :
    * 		username, newpassword
    * 
    * */
   void updatePassword(@Param("username")int username, @Param("newpassword")String newpassword);
    
}